### ISSUE TITLE
Create Airbyte connection using Airbyte S3 destination and validate the Parquet format output

### ISSUE THREAD

**Issue by hokam** [blotoutio/airbyte#98]
Create a connection using shopify and s3 as destination and validate the functionality for nested input data where we have array, struct or map type of data in input.

**Comment by hokam** [comment]
Validated the functionality by creating connection on airbyte. It worked with nested schema and correctly writing data in s3 in parquet format, but it fails when the incoming record doesn't match with the schema that we get for that table while creating connection.

We get following exception when such scenario comes:

destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$1(IntegrationRunner.java:163) ~[io.airbyte.airbyte-integrations.bases-base-java-0.35.60-alpha.jar:?]
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.sentry.AirbyteSentry.executeWithTracing(AirbyteSentry.java:54) [io.airbyte.airbyte-integrations.bases-base-java-0.35.60-alpha.jar:?]
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.sentry.AirbyteSentry.executeWithTracing(AirbyteSentry.java:38) [io.airbyte.airbyte-integrations.bases-base-java-0.35.60-alpha.jar:?]
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:163) [io.airbyte.airbyte-integrations.bases-base-java-0.35.60-alpha.jar:?]
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:105) [io.airbyte.airbyte-integrations.bases-base-java-0.35.60-alpha.jar:?]
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.s3.S3Destination.main(S3Destination.java:51) [io.airbyte.airbyte-integrations.connectors-destination-s3-0.35.60-alpha.jar:?]
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - Caused by: org.apache.avro.AvroTypeException: Could not evaluate union, field customer is expected to be one of these: NULL, RECORD. If this is a complex type, check if offending field: customer.tax_exemptions adheres to schema.
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at tech.allegro.schema.json2avro.converter.AvroTypeExceptions.unionException(AvroTypeExceptions.java:28) ~[converter-0.2.11-SNAPSHOT.jar:?]
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.readUnion(JsonGenericRecordReader.java:289) ~[converter-0.2.11-SNAPSHOT.jar:?]
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:196) ~[converter-0.2.11-SNAPSHOT.jar:?]
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:170) ~[converter-0.2.11-SNAPSHOT.jar:?]
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.lambda$readRecord$0(JsonGenericRecordReader.java:152) ~[converter-0.2.11-SNAPSHOT.jar:?]
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.readRecord(JsonGenericRecordReader.java:141) ~[converter-0.2.11-SNAPSHOT.jar:?]
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:127) ~[converter-0.2.11-SNAPSHOT.jar:?]
destination - 2022-03-29 08:57:49 INFO DefaultAirbyteStreamFactory(lambda$create$0):61 - 	... 17 more
